// <auto-generated />
namespace DM.AbpZeroTemplate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update_VisiteTime_To_CollectionTime_IN_KeyHolding : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_VisiteTime_To_CollectionTime_IN_KeyHolding));
        
        string IMigrationMetadata.Id
        {
            get { return "201609031227279_Update_VisiteTime_To_CollectionTime_IN_KeyHolding"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
