// <auto-generated />
namespace DM.AbpZeroTemplate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update_HomOwerId_To_HomeOwerId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_HomOwerId_To_HomeOwerId));
        
        string IMigrationMetadata.Id
        {
            get { return "201607280305581_Update_HomOwerId_To_HomeOwerId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
