// <auto-generated />
namespace DM.AbpZeroTemplate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update_FlatNumbers_TableName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_FlatNumbers_TableName));
        
        string IMigrationMetadata.Id
        {
            get { return "201701181548368_Update_FlatNumbers_TableName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
