// <auto-generated />
namespace DM.AbpZeroTemplate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_HomeOwer_Name : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_HomeOwer_Name));
        
        string IMigrationMetadata.Id
        {
            get { return "201702130813371_Add_HomeOwer_Name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
